### ISSUE TITLE
Params in main function

### ISSUE THREAD

**Issue by fjinkis** [Kelsus/api-spot-package#9]
# Expected Behavior

You should be able to call the main process without parameters in order to read all the values from the environment variables

# Current Behavior

If you don't provide any param, the package fails with `TypeError: Cannot read property 'slice' of undefined`

# Proposed Solution

I think that the function `parseActivityParameters` should handle the alternative of omit params, specially, with the following line
https://github.com/Kelsus/api-spot-package/blob/66dff7ed4234e07cb01948c664741e1df284826f/index.js#L106

# Other information

Some deploy logs:
```shell
***************************************************************************
Notifying deploy spot API
***************************************************************************
-- Found a CI env variable --
Checking for CI variables: CIRCLE_PROJECT_REPONAME,CIRCLE_BRANCH,CIRCLE_BUILD_NUM
Found variable: CIRCLE_PROJECT_REPONAME
Found variable: CIRCLE_BRANCH
Found variable: CIRCLE_BUILD_NUM
Got 'version' 1.3.18 from package.json. (It might be replaced with an Env variable)
** Checking SPOT Env variables **
Deploy SPOT check for the variables: APP_NAME,SERVICE_NAME,ENVIRONMENT_NAME,BUILD_STATUS,VERSION,APP_URL
Found variable: SERVICE_NAME
Cannot parse activity parameters: TypeError: Cannot read property 'slice' of undefined
    at Object.parseActivityParameters (/home/circleci/project/node_modules/@kelsus/api-spot-package/index.js:106:37)
    at Object.main (/home/circleci/project/node_modules/@kelsus/api-spot-package/index.js:400:26)
    at EmptyToolbox.toolbox.reportSpot (/home/circleci/project/node_modules/@kbs/kelsus-deploy/src/extensions/report-spot.js:4:47)
    at Command.run (/home/circleci/project/node_modules/@kbs/kelsus-deploy/src/commands/cli-deploy.js:82:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
--Getting git repo info
TypeError: Cannot destructure property 'environment' of 'activityParameters' as it is undefined.
    at Object.buildActivityBody (/home/circleci/project/node_modules/@kelsus/api-spot-package/index.js:243:7)
    at Object.main (/home/circleci/project/node_modules/@kelsus/api-spot-package/index.js:402:51)
    at EmptyToolbox.toolbox.reportSpot (/home/circleci/project/node_modules/@kbs/kelsus-deploy/src/extensions/report-spot.js:4:47)
    at Command.run (/home/circleci/project/node_modules/@kbs/kelsus-deploy/src/commands/cli-deploy.js:82:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by cesaraugustogarcia** [comment]
Now we support invoking this package either using `npx` or by installing the dependency and calling the `main` function. Issue has been confirmed to be resolved by @fjinkis .
